### ISSUE TITLE
可否新增认证网关，以适配其他学校

### ISSUE THREAD

**Issue by w11235** [vouv/SrunBar#1]
你好，我没有编程基础，不会操作那些命令行工具，发现你的客户端即可爱又方便，可惜我们学校无法使用。

我现在用的是这个pythons脚本：https://github.com/ice-tong/SrunClient ，通过修改认证网址可以在Windows上使用。但是在Mac上却用不了。

所以我想询问一下，能否在客户端中增加设置让我自定义认证网关呢？

**Comment by vouv** [comment]
> 你好，我没有编程基础，不会操作那些命令行工具，发现你的客户端即可爱又方便，可惜我们学校无法使用。
> 
> 我现在用的是这个pythons脚本：https://github.com/ice-tong/SrunClient ，通过修改认证网址可以在Windows上使用。但是在Mac上却用不了。
> 
> 所以我想询问一下，能否在客户端中增加设置让我自定义认证网关呢？

我看了一下，这个项目登录过程和我针对我们学校实现的不一样，恐怕仅仅修改网关地址也不能达到你想要的效果
